export const AUTH = {
  BASE: 'auth',
  LOGIN: 'login',
  REGISTER: 'register',
  REFRESH_TOKEN: 'refresh-token',
  LOGOUT: 'logout',
  ME: 'me',
  UPDATE_ME: 'me',
  UPDATE_PASSWORD: 'me/password',
  REQUEST_EMAIL_CHANGE: 'me/email',
  CONFIRM_EMAIL_CHANGE: 'me/email/confirm',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  VERIFY_EMAIL: 'verify-email',
  RESEND_VERIFICATION_EMAIL: 'resend-verification-email',
  DELETE_ACCOUNT: 'me',
} as const;
