export const LEARNING = {
  BASE: 'learning',
  RANDOM_WORD: 'random-word',
  TODAY_WORD: 'today-word',
  WORD_PROGRESS: 'words/:wordId/progress',
  REVIEW_QUEUE: 'review-queue',
  WORD_REVIEW: 'words/:wordId/review',
  WORD_SCHEDULE: 'words/:wordId/schedule',
  WORD_QUIZ: 'words/:wordId/quiz',
  QUIZ_RESULTS: 'quiz-results',
  DASHBOARD: 'dashboard',
  ACTIVITY: 'activity',
  ACTIVITY_DETAIL: 'activity/detail',
  LEARNER_XP: 'learner/xp',
  LIBRARY: 'library',
  FAVORITE_WORDS: 'favorite-words',
  FAVORITE_WORD: 'favorite-words/:wordId',
  BADGES: 'user/badges',
  PROFILES_DAILY_STATES: 'profiles/daily-states',
} as const;
